import type { GetStaticProps } from 'next'
import styles from '../styles/Home.module.css'
import Head from "next/head"
import {sanityClient, urlFor} from "../lib/sanity";

type Recipe = {
  title: string
}

type HomeProps = {
  recipes: Recipe[]
}

const Home = ({ recipes }: HomeProps) => {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {recipes[0].title}!
        </h1>
      </main>
    </div>
  )
}


export const getStaticProps : GetStaticProps = async () => {
  return {
    props: {
      recipes: [{title: "tega"}]
    }
  }
}

export default Home;